PaginationParamLimit:
  name: limit
  in: query
  schema:
    type: integer
    minimum: 1
    maximum: 100
    example: 99
PaginationParamOffset:
  name: offset
  in: query
  schema:
    type: integer
    minimum: 0
    example: 0
UserIdParam:
  name: id
  in: path
  schema:
    $ref: './schemas.yaml#/UUID'
  required: true
