version: '3'
services:
  node-app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      NODE_ENV: development
      REDIS_URL: redis://redis:6379
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - /app/node_modules
    links:
      - redis
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    expose:
      - 6379
